/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_halfninja_videokit_Videokit */

#ifndef _Included_uk_co_halfninja_videokit_Videokit
#define _Included_uk_co_halfninja_videokit_Videokit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_halfninja_videokit_Videokit
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_co_halfninja_videokit_Videokit_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
